spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/car_db?useSSL=false&serverTimezone=UTC
    password: admin123
  jpa:
    properties:
      hibernate:
        dialect:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: car
